import "bootstrap/dist/css/bootstrap.min.css";

import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="d-flex flex-column min-vh-100">
          <Header />
          {/* <Sidebar /> */}
          <main className="flex-grow-1">{children}</main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
